"""Generate the JavaScript reference tokenizer for compact-alignments consumers.

WHY THIS IS GENERATED, NOT HAND-WRITTEN: compact-alignments addresses target words by POSITION in the
verse's own tokenized text, so a consumer must reproduce `usj_source.tokenize()` exactly or every
position after the first divergence silently resolves to the wrong word (the format's known failure
mode — see docs/compact-alignments.md's ACT 1:3/ind_ags case, where counting "40" as a token put a
client off by one for the rest of the verse). A hand-maintained port would drift from the Python the
first time either changes; emitting it from the same source of truth makes drift impossible.

The one thing JS cannot do natively is `unicodedata.combining()` — there is no canonical-combining-class
API in ECMAScript — so the exact set is baked in here as ranges (934 code points, 196 ranges, ~2.5 KiB).

    python3 pipeline/scripts/gen_js_tokenizer.py --out publish/compact-alignments/tokenize.js
    node --input-type=module -e "import {tokenize} from './tokenize.js'; ..."   # verify
"""
from __future__ import annotations

import argparse
import unicodedata
from pathlib import Path

from lexeme_aligner.usj_source import TOKENIZER_VERSION

_HEADER = """// GENERATED by pipeline/scripts/gen_js_tokenizer.py — do not edit by hand.
// Reference tokenizer for the `bcv-commons/compact-alignments` dataset, byte-for-byte equivalent to the
// producing side's Python `usj_source.tokenize()`.
//
// WHY YOU NEED IT: compact-alignments addresses target words by POSITION in the verse's own tokenized
// text, never by repeating the word. Tokenize differently and every position after the first divergence
// resolves to the WRONG word, silently — the content hash in the filename cannot catch it, because that
// hash covers the verse TEXT, which is identical either way.
//
// NOT plain whitespace/punctuation splitting. A token is a maximal run of Unicode letters + combining
// marks (\\p{L}/\\p{M}); punctuation, whitespace AND digits are separators producing no token (a bare
// "40" is invisible to this tokenizer, not its own token). Scripts written without spaces between words
// are then segmented by rule: Han per character, Japanese at kana/script boundaries, Myanmar per syllable.
//
// TOKENIZER_VERSION is published in the dataset manifest. If it does not match the version this file
// implements, REFUSE TO DECODE rather than risk silently misaligned positions.

export const TOKENIZER_VERSION = %(version)r;
"""

_BODY = r"""
// --- canonical combining class != 0 (generated; JS has no unicodedata.combining) ---
const CCC = %(ccc)s;

function hasCombiningClass(cp) {
  let lo = 0, hi = CCC.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cp < CCC[mid][0]) hi = mid - 1;
    else if (cp > CCC[mid][1]) lo = mid + 1;
    else return true;
  }
  return false;
}

// Myanmar VIRAMA (stacks a consonant) + ASAT (kills a syllable-final one). These share the virama
// combining class with the Indic marks strip_marks drops, but they are not optional diacritics — they
// carry the syllable structure the Myanmar segmenter reads, so they are exempt.
const MYANMAR_KEEP = new Set([0x1039, 0x103a]);

// Variation selectors choose a GLYPH form and carry no linguistic content, but their combining class is
// 0 so they survive the filter above and would split one word into two vocabulary entries.
function isVariationSelector(cp) {
  return (cp >= 0xfe00 && cp <= 0xfe0f) || (cp >= 0xe0100 && cp <= 0xe01ef);
}

export function stripMarks(text) {
  let out = "";
  for (const ch of text.normalize("NFC")) {
    const cp = ch.codePointAt(0);
    if ((!hasCombiningClass(cp) || MYANMAR_KEEP.has(cp)) && !isVariationSelector(cp)) out += ch;
  }
  return out;
}

const LETTER_OR_MARK = /[\p{L}\p{M}]/u;

function cjkClass(cp) {
  if ((cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf) ||
      (cp >= 0xf900 && cp <= 0xfaff)) return "han";
  if (cp >= 0x3040 && cp <= 0x309f) return "hira";
  if (cp >= 0x30a0 && cp <= 0x30ff) return "kata";
  return null;
}

function isMyaConsonant(cp) {
  return ((cp >= 0x1000 && cp <= 0x102a) || cp === 0x103f || (cp >= 0x1050 && cp <= 0x1055) ||
          (cp >= 0x105a && cp <= 0x105d) || cp === 0x1061 || (cp >= 0x1065 && cp <= 0x1066) ||
          (cp >= 0x106e && cp <= 0x1070) || (cp >= 0x1075 && cp <= 0x1081) || cp === 0x108e ||
          (cp >= 0xa9e0 && cp <= 0xa9e4) || (cp >= 0xa9e7 && cp <= 0xa9ef) ||
          (cp >= 0xa9fa && cp <= 0xa9fe) || (cp >= 0xaa60 && cp <= 0xaa6f) ||
          (cp >= 0xaa71 && cp <= 0xaa76) || cp === 0xaa7a || (cp >= 0xaa7e && cp <= 0xaa7f));
}

const MYA_VIRAMA = 0x1039, MYA_ASAT = 0x103a, MYA_EVOWEL = 0x1031;

// A syllable starts at a consonant, or at U+1031 (written BEFORE its consonant but pronounced after).
// It does not start when the consonant is stacked under a virama, nor right after U+1031, nor after an
// asat — an asat-killed consonant closes the current syllable instead of opening the next.
function myaSyllables(tok) {
  const chars = Array.from(tok);
  const out = [];
  let cur = [];
  for (let i = 0; i < chars.length; i++) {
    const cp = chars[i].codePointAt(0);
    const prev = i ? chars[i - 1].codePointAt(0) : 0;
    if ((isMyaConsonant(cp) || cp === MYA_EVOWEL) && cur.length &&
        prev !== MYA_VIRAMA && prev !== MYA_EVOWEL && prev !== MYA_ASAT) {
      out.push(cur.join("")); cur = [];
    }
    cur.push(chars[i]);
  }
  if (cur.length) out.push(cur.join(""));
  return out;
}

function splitUnspaced(tok) {
  const chars = Array.from(tok);
  if (chars.some((c) => isMyaConsonant(c.codePointAt(0)))) return myaSyllables(tok);
  if (!chars.some((c) => cjkClass(c.codePointAt(0)))) return [tok];
  const out = [];
  let cur = [], curCls = null;
  for (const ch of chars) {
    const cls = cjkClass(ch.codePointAt(0));
    if (cls === "han") {                       // one token per Han character
      if (cur.length) { out.push(cur.join("")); cur = []; curCls = null; }
      out.push(ch);
    } else if (cls !== curCls && cur.length) { // script boundary
      out.push(cur.join("")); cur = [ch]; curCls = cls;
    } else {
      cur.push(ch); curCls = cls;
    }
  }
  if (cur.length) out.push(cur.join(""));
  return out;
}

export function tokenize(text) {
  const out = [];
  let cur = [];
  for (const ch of stripMarks(text)) {
    if (LETTER_OR_MARK.test(ch)) cur.push(ch);
    else if (cur.length) { out.push(...splitUnspaced(cur.join(""))); cur = []; }
  }
  if (cur.length) out.push(...splitUnspaced(cur.join("")));
  return out;
}
"""


def ccc_ranges() -> list[tuple[int, int]]:
    cps = [cp for cp in range(0x110000) if unicodedata.combining(chr(cp))]
    out, start, prev = [], cps[0], cps[0]
    for cp in cps[1:]:
        if cp == prev + 1:
            prev = cp
            continue
        out.append((start, prev))
        start = prev = cp
    out.append((start, prev))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("publish/compact-alignments/tokenize.js"))
    args = ap.parse_args()
    ranges = ccc_ranges()
    js = ",".join(f"[{a},{b}]" for a, b in ranges)
    body = _BODY % {"ccc": f"[{js}]"}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text((_HEADER % {"version": TOKENIZER_VERSION}).replace("'", '"') + body,
                        encoding="utf-8")
    print(f"[gen_js_tokenizer] {args.out} — tokenizer v{TOKENIZER_VERSION}, "
          f"{len(ranges)} combining-class ranges")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
