"""USJ source adapter — read a book's USJ, emit per-verse target-language tokens.

The only format-specific code in the pipeline (docs/aligner-plan.md §Generic input):
walk the USJ `content` tree in document order, track chapter/verse markers, collect
translatable text, and EXCLUDE apparatus by element type/marker (notes, headings,
titles, intro material) so footnote/heading words can never leak into the alignment.

Tokenization is generic unicode word-splitting; language-specific normalization
(e.g. Indonesian clitic stripping) lives in gloss_align, not here.
"""
from __future__ import annotations

import difflib
import json
import re
import sys
import unicodedata
from pathlib import Path

from lexeme_aligner import config as _config

# Non-scripture paragraph markers (digits stripped before lookup): headers, titles,
# section headings, psalm titles (d), speaker lines, intro material. `b` is a blank line.
_SKIP_PARA = {
    "h", "toc", "mt", "imt", "ms", "mr", "s", "sr", "r", "d", "sp", "sd",
    "cl", "cp", "ca", "ide", "rem", "b", "ib", "ip", "is", "io", "iot",
    "ili", "im", "imi", "ipi", "iq", "ie", "periph", "restore", "lit",
}
# Character markers whose text is NOT translation text (alternate chapter/verse numbers).
_SKIP_CHAR = {"va", "vp", "ca", "cp", "fv", "fm"}

_WORD_RE = re.compile(r"[^\W\d_]+", re.UNICODE)

# Some editions inline editorial/study-note expansions directly in verse text using square brackets
# (not USFM \f footnote markers, so _walk_verses's `t == "note"` skip never sees them) — live case:
# Svenska Kärnbibeln ("en expanderad översättning") wraps multi-sentence commentary in [...] mid-verse.
# BUT [...] is not a uniform convention across editions — e.g. Young's Literal Translation (`engy`) uses
# it for genuinely-translated SUPPLIED words (no literal source-language counterpart), which must NOT be
# stripped. So this is applied PER EDITION, opt-in only, never automatically: an edition's verse text is
# only ever run through this if `config/text_strip_rules.json` explicitly sets `strip_brackets: true` for
# its edition tag (see `_rules_for`/`_load_strip_rules` below). By default NOTHING is stripped — every
# edition gets its raw text, brackets and parens included, exactly as ingested. `config/
# text_strip_report.md` (generated by `pipeline/scripts/text_strip_candidates.py`) surfaces the clues
# (span-length distribution, noise-pattern hits, samples) a human reviews before writing that decision.
# Strip innermost-first (loop) so accidental nesting doesn't leave a stray bracket; a bare stray "[" or
# "]" (unbalanced, rare) is left as-is rather than risk eating real text.
_BRACKET_NOTE_RE = re.compile(r"\[[^\[\]]*\]")


def _strip_bracket_notes(text: str) -> str:
    prev = None
    while prev != text:
        prev, text = text, _BRACKET_NOTE_RE.sub(" ", text)
    return text


# Parens are also opt-in (`strip_parens_noise: true` per edition in config/text_strip_rules.json), same
# reasoning as brackets above — and even where enabled, parens get a DISCRIMINATING strip rather than a
# blanket one: on swk, ~83% of parenthetical spans are short alternate/amplified Swedish glosses genuinely
# worth aligning (e.g. "(blygdes)", "(oförtjänt kärlek, god favör)" — the "enhanced translation" content
# publishing-principles.md #4 says to keep), vs ~17% real noise: source-language citations ("hebr.
# chesed", "gr. logos"), cross-references ("1 Mos 1:1", "vers 17"), metalinguistic glosses ("ordagrant
# ...", "... betyder ..."), and era/date annotations ("735-715 f.Kr."). So `_paren_is_noise` classifies
# each span and either drops it or unwraps the kept text back into the sentence. Verified the noise
# patterns don't misfire on ordinary short content and this doesn't just rediscover the bracket case
# under another name.
_PAREN_RE = re.compile(r"\(([^()]*)\)")
_PAREN_CITATION_RE = re.compile(r"\b(hebr|grek|gr|aram)\.", re.I)
_PAREN_VERSE_REF_RE = re.compile(r"\bvers\.?\s?\d+\b", re.I)
_PAREN_BOOK_REF_RE = re.compile(r"[A-ZÅÄÖ]\w*\.?\s?\d+:\d+")
_PAREN_LITERAL_RE = re.compile(r"\bordagrant\b", re.I)
_PAREN_MEANS_RE = re.compile(r"\bbetyder\b", re.I)
# Swedish-specific BC/AD abbreviations (era/date annotations, e.g. "735-715 f.Kr."). A generic
# "ends with a period" rule was tried first but misfires badly cross-edition — other translations
# routinely have full, legitimate sentences of scripture text inside parens (verified: 14/41 in
# ayzyss, 107/165 in porwtc would have been wrongly dropped) — so this stays narrowly Swedish-lexical
# like the other rules, not structural.
_PAREN_ERA_RE = re.compile(r"\b[fe]\.\s?kr\.", re.I)


def _paren_is_noise(content: str) -> bool:
    c = content.strip()
    if not c:
        return True
    return bool(
        _PAREN_CITATION_RE.search(c)
        or _PAREN_VERSE_REF_RE.search(c)
        or _PAREN_BOOK_REF_RE.search(c)
        or _PAREN_LITERAL_RE.search(c)
        or _PAREN_MEANS_RE.search(c)
        or _PAREN_ERA_RE.search(c)
    )


def _strip_paren_notes(text: str) -> str:
    # Kept content is padded with spaces on both sides, not spliced back in bare — some editions run a
    # paren directly against its neighbor with no space ("Simeons(Shimons) söner"; found via the compact-
    # alignments raw-position remap work, where it showed up as a bogus merged "SimeonsShimons" token).
    # Since tokenize() only cares about letter/mark runs, extra whitespace where there's already a real
    # word boundary is harmless — this can only ever ADD a missing boundary, never remove a real one.
    prev = None
    while prev != text:
        prev = text
        text = _PAREN_RE.sub(lambda m: " " if _paren_is_noise(m.group(1)) else f" {m.group(1)} ", text)
    return text


# Per-edition strip decisions (config/text_strip_rules.json), keyed by the edition tag as it appears in
# the ingest-cache dir name (pipeline/work/ingest-cache/usj-<tag>/...). Missing file / missing entry /
# missing field all mean "don't strip" — silence is the safe default, never an error.
_EDITION_TAG_RE = re.compile(r"^usj-(.+)$")
_strip_rules_cache: dict | None = None


def _load_strip_rules() -> dict:
    global _strip_rules_cache
    if _strip_rules_cache is None:
        try:
            data = json.loads(_config.TEXT_STRIP_RULES.read_text(encoding="utf-8"))
            _strip_rules_cache = data.get("editions", {})
        except (FileNotFoundError, OSError, ValueError):
            _strip_rules_cache = {}
    return _strip_rules_cache


def _rules_for(usj_path: Path) -> dict:
    m = _EDITION_TAG_RE.match(Path(usj_path).parent.name)
    return _load_strip_rules().get(m.group(1), {}) if m else {}


def strip_marks(text: str) -> str:
    """NFC, then drop combining marks (Unicode Mn) — Arabic harakat, Hebrew points, etc. Otherwise the
    word regex shatters a diacritized word at every mark (فِي → ف, ي). Precomposed Latin accents (é, å)
    survive NFC as single code points, so French/Swedish are unaffected; only decomposed marks go."""
    return "".join(c for c in unicodedata.normalize("NFC", text) if not unicodedata.combining(c))


def _base_marker(marker: str) -> str:
    return (marker or "").rstrip("0123456789")


def _walk_verses(usj_path: Path, warn=sys.stderr, rules: dict | None = None):
    """Shared walker for read_verses/read_verse_ranges — yields (chapter, verse_start, verse_end,
    text_piece) per text-bearing item, verse_end == verse_start for a bare (non-range) marker.

    `rules`: if None (the normal case), looked up from config/text_strip_rules.json by edition tag
    (see `_rules_for`). Pass `{}` explicitly to force raw text regardless of config — used by
    `read_raw_verses`/the text_strip_candidates report to see an edition's un-stripped text even if a
    strip decision is already on file for it."""
    usj = json.loads(Path(usj_path).read_text(encoding="utf-8"))
    state = {"ch": 0, "vs": 0, "ve": 0}
    seen_unknown: set[str] = set()
    if rules is None:
        rules = _rules_for(usj_path)

    def emit(text: str):
        if rules.get("strip_brackets"):
            text = _strip_bracket_notes(text)
        if rules.get("strip_parens_noise"):
            text = _strip_paren_notes(text)
        if state["ch"] and state["vs"] and text:
            yield (state["ch"], state["vs"], state["ve"], text)

    def walk(items):
        for it in items:
            if isinstance(it, str):
                yield from emit(it)
                continue
            t = it.get("type")
            if t == "chapter":
                state["ch"] = int(re.match(r"\d+", str(it.get("number", "0"))).group())
                state["vs"] = state["ve"] = 0
            elif t == "verse":
                # a range marker ("3-4") keeps BOTH ends — read_verses() historically only kept the
                # first number, silently discarding which OTHER source verses share this target text.
                m = re.match(r"(\d+)(?:-(\d+))?", str(it.get("number", "0")))
                if m:
                    state["vs"] = int(m.group(1))
                    state["ve"] = int(m.group(2)) if m.group(2) else state["vs"]
                else:
                    state["vs"] = state["ve"] = 0
            elif t == "note":
                continue                                    # footnotes / cross-refs: never text
            elif t == "para":
                base = _base_marker(it.get("marker", ""))
                if base in _SKIP_PARA:
                    continue
                if base not in {"p", "m", "po", "pr", "cls", "pmo", "pm", "pmc", "pmr",
                                "pi", "mi", "nb", "pc", "ph", "q", "qr", "qc", "qa",
                                "qac", "qm", "qd", "lh", "li", "lf", "lim", "tr", "tc",
                                "tcr", "th", "thr"} and base not in seen_unknown:
                    seen_unknown.add(base)
                    print(f"[usj] note: unknown para marker '{it.get('marker')}' — included",
                          file=warn)
                if it.get("content"):
                    yield from walk(it["content"])
            elif t == "char":
                if _base_marker(it.get("marker", "")) in _SKIP_CHAR:
                    continue
                if it.get("content"):
                    yield from walk(it["content"])
            elif it.get("content"):
                yield from walk(it["content"])

    yield from walk(usj.get("content", []))


def read_verses(usj_path: Path, warn=sys.stderr, *, rules: dict | None = None) -> dict[tuple[int, int], str]:
    """{(chapter, verse): text} for one book's USJ file. Verse ranges ("1-2") are
    keyed by their first number. Unknown para markers are included but logged once."""
    verses: dict[tuple[int, int], list[str]] = {}
    for ch, vs, _ve, text in _walk_verses(usj_path, warn, rules=rules):
        verses.setdefault((ch, vs), []).append(text)
    return {k: " ".join(parts) for k, parts in verses.items()}


def read_verse_ranges(usj_path: Path, warn=sys.stderr, *, rules: dict | None = None) -> dict[tuple[int, int], dict]:
    """{(chapter, verse_start): {"text": str, "verse_end": int}} — like read_verses but preserves
    the END of a verse RANGE marker ("3-4" -> verse_start=3, verse_end=4, text=both verses' combined
    translation), instead of silently discarding it. verse_end == verse_start for a normal single-verse
    marker. Use this (not read_verses) wherever a caller needs to know if a target block actually
    covers MULTIPLE source verses — e.g. reverse_align_check.py / a future build_corpus range-pooling."""
    verses: dict[tuple[int, int], dict] = {}
    for ch, vs, ve, text in _walk_verses(usj_path, warn, rules=rules):
        key = (ch, vs)
        if key not in verses:
            verses[key] = {"text": [], "verse_end": ve}
        verses[key]["text"].append(text)
        verses[key]["verse_end"] = max(verses[key]["verse_end"], ve)
    return {k: {"text": " ".join(v["text"]), "verse_end": v["verse_end"]} for k, v in verses.items()}


def read_raw_verses(usj_path: Path, warn=sys.stderr) -> dict[tuple[int, int], str]:
    """Like read_verses, but always raw — bypasses config/text_strip_rules.json even if the edition has
    a strip decision on file. For tooling that needs to see what's actually in the source (e.g.
    text_strip_candidates.py), not what the aligner currently reads."""
    return read_verses(usj_path, warn, rules={})


def tokenize(text: str) -> list[str]:
    """Generic unicode word tokens, order preserved (normalization happens later). A token is a run of
    letters + their combining marks (a grapheme cluster), so Indic/diacritized scripts tokenize by WORD,
    not shatter at every vowel sign — दाऊद stays one token, not द+ऊद (the old `[^\\W\\d_]+` regex broke at
    spacing marks like the Mc matra ा). `strip_marks` still drops nonspacing marks (Arabic harakat, Hebrew
    points, Indic viramas) for match-normalisation; spacing marks stay inside the cluster. Latin/Cyrillic
    unaffected (no combining marks after NFC)."""
    toks: list[str] = []
    cur: list[str] = []
    for ch in strip_marks(text):
        if unicodedata.category(ch)[0] in ("L", "M"):        # letter or combining mark → part of the word
            cur.append(ch)
        elif cur:
            toks.append("".join(cur))
            cur = []
    if cur:
        toks.append("".join(cur))
    return toks


def remap_clean_to_raw(raw_text: str, clean_text: str) -> list[int]:
    """result[clean_idx] = raw_idx (or -1 if no confident match was found — see below) for every token in
    tokenize(clean_text). Used at compact-alignment publish time (compact_align.py) to convert an
    alignment's target positions — computed against clean (opt-in stripped) text, since that's what the
    aligner actually trained on — into positions in the edition's RAW, unmodified text, so a client who
    tokenizes their own untouched copy of the verse gets the right word.

    Correct by construction, not by guessing: `_strip_bracket_notes`/`_strip_paren_notes` only ever DELETE
    substrings or drop parenthesis punctuation around KEPT text — they never reorder or rewrite surviving
    words. So clean_text's tokens are always an exact, order-preserving subsequence of raw_text's tokens;
    the ones that exist only in raw (inside a stripped span) are exactly the ones with no entry in the
    returned list — which is what makes them "unaligned" for free under the compact format's existing
    absence-means-unaligned convention, once a caller only ever looks up indices this function actually
    returns.

    Diffs the TOKEN sequences (stdlib difflib on the two tokenize() outputs), not the raw characters —
    tried a character-level diff first and it broke on real data: a stripped bracket's fragment ("en",
    from "...en som skär...") coincidentally matched the trailing two characters of a SURVIVING word
    elsewhere ("häl-EN"), since SequenceMatcher has no concept of word boundaries and a long deleted
    span (swk's brackets run to hundreds of words) gives it plenty of room to find that kind of spurious
    short match. Diffing whole tokens instead makes a wrong match structurally impossible — two elements
    only ever compare equal if they're the same complete word, matching how `_paren_is_noise`/friends
    already operate on words either kept or dropped whole, never split mid-word."""
    if raw_text == clean_text:
        return list(range(len(tokenize(clean_text))))
    raw_toks = tokenize(raw_text)
    clean_toks = tokenize(clean_text)
    out = [-1] * len(clean_toks)
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, raw_toks, clean_toks, autojunk=False).get_opcodes():
        if tag == "equal":
            for k in range(i2 - i1):
                out[j1 + k] = i1 + k
    if -1 in out:
        # Leave the -1 sentinel in place at its clean-side index rather than compacting the list —
        # a caller indexes this by the ORIGINAL clean token position (e.g. from an alignment's t_idx),
        # so removing an entry would shift every later index and silently point at the wrong word.
        n_missing = out.count(-1)
        print(f"[usj_source] warn: remap_clean_to_raw couldn't place {n_missing}/{len(out)} clean "
              "token(s) in the raw text — those positions come back as -1, callers should skip them",
              file=sys.stderr)
    return out
